### ISSUE TITLE
Addon doesn't start in my Openelec RPI2

### ISSUE THREAD

**Issue by fluffymadness** [dead/moonlight-openelec-rpi2#16]
```
21:29:38 1769.966309 T:1541153856  NOTICE: -->Python Interpreter Initialized<--
21:29:38 1770.286987 T:1541153856   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.OSError'>
                                            Error Contents: libmoonlight-common.so.0: cannot open shared object file: No such file or directory
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.moonlight/addon.py", line 78, in <module>
                                                index()
                                              File "/storage/.kodi/addons/script.moonlight/addon.py", line 25, in index
                                                gs = LibGameStream(addon.getAddonInfo("path") + "/lib")
                                              File "/storage/.kodi/addons/script.moonlight/resources/moonlight.py", line 36, in __init__
                                                self.gslib = ctypes.cdll.LoadLibrary(os.path.join(libpath, "libgamestream.so.0"))
                                              File "/home/stephan/projects/openelec-6.0/build.OpenELEC-RPi2.arm-6.0.3/Python-2.7.3/.install_pkg/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
                                              File "/home/stephan/projects/openelec-6.0/build.OpenELEC-RPi2.arm-6.0.3/Python-2.7.3/.install_pkg/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
                                            OSError: libmoonlight-common.so.0: cannot open shared object file: No such file or directory
                                            -->End of Python script error report<--

```

Didn't test the older releases, maybe something went wrong with my installation...
Will test this again tomorrow.
And thx for writing this addon :)

**Comment by dead** [comment]
Please try this new release https://github.com/dead/moonlight-openelec-rpi2/releases/download/v1.0.11/script.moonlight.zip :smile:

**Comment by fluffymadness** [comment]
Everything is working perfect now with my Dualshock 3's :)
One little question: Does this addon also support WakeOnLan of the paired computer?

**Comment by rapidreporter** [comment]
Hi, for wake on lan of the paired computer I personaly use this.
https://github.com/sciguy14/Remote-Wake-Sleep-On-LAN-Server 
works perfekt and you can the pc also power off, and you could configer all of your pcs to easyly wake up :)
Another good thing is that you are able to set a password.

bye and have a nice day

**Comment by fluffymadness** [comment]
Thx for the link. Shutdown works perfect for me via steam big picture mode.
I'll just look for a wake-on-lan addon for kodi to send the magic packet, but still it would be awesome if the addon had an option that could be activated to autosend the magic packet, when the host is not online or something like that.
