### ISSUE TITLE
Moonlight crashes right after starting

### ISSUE THREAD

**Issue by datakneus** [dead/moonlight-openelec-rpi2#36]
I have a Raspberry 2 running OSMC and the latest version of Moonlight (1.0.3). After starting OSMC and starting Moonlight I immediately get an error. This is what's in the log:
>17:11:31  48.344341 T:1688204272   ERROR: ExecuteAsync - Not executing non-existing script /home/osmc/.kodi/addons/script.moonlight/service.py
17:13:03 140.786224 T:1510732784   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.OSError'>
                                            Error Contents: libcrypto.so.32: cannot open shared object file: No such file or directory
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/script.moonlight/addon.py", line 80, in <module>
                                                index()
                                              File "/home/osmc/.kodi/addons/script.moonlight/addon.py", line 27, in index
                                                gs = LibGameStream(addon.getAddonInfo("path") + "/lib")
                                              File "/home/osmc/.kodi/addons/script.moonlight/lib/moonlight.py", line 41, in __init__
                                                self.gslib = ctypes.cdll.LoadLibrary(os.path.join(libpath, "libgamestream.so.0"))
                                              File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
                                                return self._dlltype(name)
                                              File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
                                                self._handle = _dlopen(self._name, mode)
                                            OSError: libcrypto.so.32: cannot open shared object file: No such file or directory
                                            -->End of Python script error report<--
17:13:03 141.005783 T:1956762544   ERROR: GetDirectory - Error getting plugin://script.moonlight/
17:13:03 141.006088 T:1956762544   ERROR: CGUIMediaWindow::GetDirectory(plugin://script.moonlight/) failed<

Can you please help me?

**Comment by joaohkfaria** [comment]
Same problem here...

**Comment by dead** [comment]
To make this addon work in OSMC you will need to replace the binaries in the libs/ and bin/ to a OSMC compatible.

**Comment by RouHim** [comment]
Same here:

`19:02:23 T:139927710836480   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.OSError'>
                                            Error Contents: /storage/.kodi/addons/script.moonlight/lib/libmoonlight-common.so.0: wrong ELF class: ELFCLASS32
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.moonlight/addon.py", line 80, in <module>
                                                index()
                                              File "/storage/.kodi/addons/script.moonlight/addon.py", line 27, in index
                                                gs = LibGameStream(addon.getAddonInfo("path") + "/lib")
                                              File "/storage/.kodi/addons/script.moonlight/lib/moonlight.py", line 40, in __init__
                                                self.commonlib = ctypes.cdll.LoadLibrary(os.path.join(libpath, "libmoonlight-common.so.0"))
                                              File "/usr/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
                                              File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
                                            OSError: /storage/.kodi/addons/script.moonlight/lib/libmoonlight-common.so.0: wrong ELF class: ELFCLASS32
                                            -->End of Python script error report<--
19:02:23 T:139929019439232   ERROR: GetDirectory - Error getting plugin://script.moonlight/
19:02:23 T:139929019439232   ERROR: CGUIMediaWindow::GetDirectory(plugin://script.moonlight/) failed`

**Comment by ghost** [comment]
So how do i fix it? :D
I don't know how to replace the binaries :/

**Comment by Joechinchains** [comment]
Same here (crash and error on start) except I don't even have OSMC, I'm just on regular Openelec. I've tried everything from older versions of the plugin to starting from a fresh install but I haven't got Moonlight to start up even once. Here's my log if you can make sense of it.

``
21:47:54 8230.857422 T:1633248160   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.OSError'>
Error Contents: libcrypto.so.32: cannot open shared object file: No such file or directory
Traceback (most recent call last):
File "/storage/.kodi/addons/script.moonlight/addon.py", line 80, in <module>
index()
File "/storage/.kodi/addons/script.moonlight/addon.py", line 27, in index
gs = LibGameStream(addon.getAddonInfo("path") + "/lib")
File "/storage/.kodi/addons/script.moonlight/lib/moonlight.py", line 41, in __init__
self.gslib = ctypes.cdll.LoadLibrary(os.path.join(libpath, "libgamestream.so.0"))
File "/usr/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
OSError: libcrypto.so.32: cannot open shared object file: No such file or directory
-->End of Python script error report<--
21:47:54 8231.212891 T:1963868160   ERROR: GetDirectory - Error getting plugin://script.moonlight/
21:47:54 8231.212891 T:1963868160   ERROR: 
``

**Comment by burtaverde** [comment]
i have this problem if i try anything later that 1.0.11. I've yet to try the previous ones, but currently it works in openelec 8.0.3, except for controller mapping which is a bit messed up and the fact that it doesn't return to kodi once the game is closed.

**Comment by dead** [comment]
To fix the libcrypto.so.32 try this: #45
Since this is an old issue I'm going to close it, if you still need some help feel free to open it again.
