### ISSUE TITLE
Openelec Orange pi

### ISSUE THREAD

**Issue by kenthinson** [dead/moonlight-openelec-rpi2#42]
Hello. I am trying to get the addon to work with orange pi. When I try to start the addon it wont start and says check the log for errors. 

I found this in kodi.log:
Can you help me figure out how to fix it? thanks!

17:16:17 T:2629542816   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the f
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!                     
                                            Error Type: <type 'exceptions.OSError'>                              
                                            Error Contents: libcrypto.so.32: cannot open shared object file: No s
                                            Traceback (most recent call last):                                   
                                              File "/storage/.kodi/addons/script.moonlight/addon.py", line 80, in
                                                index()                                                          
                                              File "/storage/.kodi/addons/script.moonlight/addon.py", line 27, in
                                                gs = LibGameStream(addon.getAddonInfo("path") + "/lib")          
                                              File "/storage/.kodi/addons/script.moonlight/lib/moonlight.py", lin
                                                self.gslib = ctypes.cdll.LoadLibrary(os.path.join(libpath, "libga
                                              File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibr
                                              File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
                                            OSError: libcrypto.so.32: cannot open shared object file: No such fil
                                            -->End of Python script error report<--                              
17:16:17 T:3035439104   ERROR: GetDirectory - Error getting plugin://script.moonlight/                           
17:16:17 T:3035439104   ERROR: CGUIMediaWindow::GetDirectory(plugin://script.moonlight/) failed                  
17:16:17 T:2947543968   ERROR: CecLogMessage - Write: sent command error !                                       
17:16:55 T:2770334624   ERROR: Previous line repeats 65 times.                                                   
17:16:55 T:2770334624   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the f
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!                     
                                            Error Type: <type 'exceptions.OSError'>                              
                                            Error Contents: libcrypto.so.32: cannot open shared object file: No s
                                            Traceback (most recent call last):                                   
                                              File "/storage/.kodi/addons/script.moonlight/addon.py", line 80, in
                                                index()                                                          
                                              File "/storage/.kodi/addons/script.moonlight/addon.py", line 27, in
                                                gs = LibGameStream(addon.getAddonInfo("path") + "/lib")          
                                              File "/storage/.kodi/addons/script.moonlight/lib/moonlight.py", lin
                                                self.gslib = ctypes.cdll.LoadLibrary(os.path.join(libpath, "libga
                                              File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibr
- kodi.log 203/209 97%

**Comment by dead** [comment]
Please, update to Libreelec.
