### ISSUE TITLE
Upgrade to 2.4.6?

### ISSUE THREAD

**Issue by jkms** [dead/moonlight-openelec-rpi2#57]
Version 2.4.5+ is required for GFE 3.12 (and GFE likes to auto-update).

https://github.com/irtimmer/moonlight-embedded/releases/tag/v2.4.6

**Comment by cminnoy** [comment]
Any progress on this?

**Comment by dead** [comment]
In progress... 😄

**Comment by maxanier** [comment]
Is it correct that this can only be fixed with the next libreelec release?

**Comment by dead** [comment]
Nop. Going to backport It to 8.2

**Comment by taleteller** [comment]
Well this apearently did not happen, moonlight is unusable for LibreElec 8.2.x.

**Comment by maxanier** [comment]
After finally understanding how the addon (builds) work, I managed to build this with the latest versions of moonlight embedded and common c. It is working just fine with 8.2.5.
I guess I could share the file here if you want

**Comment by taleteller** [comment]
Sounds interesting, sharing the binary would save me that work.

**Comment by maxanier** [comment]
https://share.maxgb.de/dlp/file/6269424f2f032aef3d19cf8b27dfc19c57fa52ab73b905181b20b566d606c006
Edit: 
Custom build of this LibreElec/Kodi moonlight plugin by @dead for LibreElec 8.2.x. Uses latest releases of moonlight_embedded and moonlight_common_c.
Compiled for RPi2 (ARM)

**Comment by taleteller** [comment]
This seems not to be an AMD64 build
```
16:37:06.787 T:140386690914048   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.OSError'>
                                            Error Contents: /storage/.kodi/addons/script.moonlight/lib/libmoonlight-common.so.3: wrong ELF class: ELFCLASS32
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.moonlight/addon.py", line 78, in <module>
                                                index()
                                              File "/storage/.kodi/addons/script.moonlight/addon.py", line 25, in index
                                                gs = LibGameStream(addon.getAddonInfo("path") + "/lib")
                                              File "/storage/.kodi/addons/script.moonlight/lib/moonlight.py", line 58, in __init__
                                                self.commonlib = ctypes.cdll.LoadLibrary(findlib("libmoonlight-common.so"))
                                              File "/usr/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
                                              File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
                                            OSError: /storage/.kodi/addons/script.moonlight/lib/libmoonlight-common.so.3: wrong ELF class: ELFCLASS32
                                            -->End of Python script error report<--
```

**Comment by maxanier** [comment]
Totally forgot to mention that :see_no_evil: 
Yeah, its a RPI2 (ARM) build. And unfortunately I do not have any other, sorry
