### ISSUE TITLE
moonlight 2.4.10

### ISSUE THREAD

**Issue by ssAxl** [dead/moonlight-openelec-rpi2#65]
Hi,

Have you plan to make an update?
Thanks!

**Comment by ssAxl** [comment]
Please?!!! Need This! :)

**Comment by dead** [comment]
Do you use LibreELEC? Which version? Going to try update it later.

**Comment by ssAxl** [comment]
Hi,

Yes, I'm using Libreelec 9.0.2 MR.
The very last GeforceExperience working with script.moonlight is v3.14.0.161.

Many thanks to have a look!

**Comment by dead** [comment]
~~script.moonlight-9.0.241.zip~~
Can you test it?

**Comment by ssAxl** [comment]
Have try this morning, doesn't work for now:
-Udpate new files (9.0.241.zip) upon old files and Geforce v3.14.0.161 on my computer:
 => Moonlight show game list (and MSTSC.EXE to stream pc desktop).
 => Start streaming, black screen and (auto) reboot of Libreelec 

-Try to delete all moonlight files and re-install to make "fresh" install (with 9.0.241.zip) and Update GeforceExperience to v3.19.0.107.
 => Moonlight successful paired with computer and show game list, but have the same problem when start streaming (black screen, then reboot).

Sorry for my english, this is not my native language.
Thank for help!

**Comment by dead** [comment]
Can you get the logs from `Userdata/addon_data/script.moonlight/service.log` ?
Thanks!

**Comment by ssAxl** [comment]
Hi,

Argh! I' don't find it.
In this folder I only have "gamecontrollerdb.txt" and "settings.xml", but no log at all?!
I search everywhere but still no log.
Any other way to help you?

Thanks to you ;)

**Comment by ssAxl** [comment]
Finally found it!
I've deactivatethe log under Libreelec.

Here it is:
stream -packetsize 1024 -bitrate 10000 -720 -fps 30 -app "PC-Axl" -keydir "/storage/.kodi/userdata/addon_data/script.moonlight/keys" -mapping "/storage/.kodi/userdata/addon_data/script.moonlight/gamecontrollerdb.txt" 192.168.0.210
/storage/.kodi/addons/script.moonlight/bin/moonlight: error while loading shared libraries: libgamestream.so.4: cannot open shared object file: No such file or directory

Hope it's help!

**Comment by dead** [comment]
Please, try again: [script.moonlight-9.0.241.zip](https://github.com/dead/script.moonlight/files/3408247/script.moonlight-9.0.241.zip)

😄

**Comment by ssAxl** [comment]
Hi,

I've try it..... and it's working again !!!! :) :) :)
At the moment, I don't have time to test all features, but i'll test it as soon as I can, and give you feedback.

Thanks again!!!!

**Comment by ssAxl** [comment]
Hi,

I've play Ghost Of A Tale via Moonlight for 2 hours yesterday (driver Geforce 431.60 and Geforce Experience v3.19.0.107):
Video, audio and features working like a charm!
Some audio lag, but I think it's coming from my Rpi3.
Last question: Is there a shortcut or anything else to leave streaming instead of reboot the computer?

Here is the .log:
stream -packetsize 2048 -bitrate 20000 -1080 -fps 60 -localaudio -app "PC-Axl" -keydir "/storage/.kodi/userdata/addon_data/script.moonlight/keys" -mapping "/storage/.kodi/userdata/addon_data/script.moonlight/gamecontrollerdb.txt" 192.168.0.210
No mapping available for Lenovo Mini Wireless Keyboard System Control (03000000ef1700001460000011010000) on /dev/input/event4

Thanks again!

**Comment by ssAxl** [comment]
Hi,

Some feedback,
After many session of A Plague Tale, with following settings:
-packetsize 2048 -bitrate 20000 -1080 -fps 60 -localaudio
I Play on LAN with a computer Intel LAN Card  => switch D-LINK DGS-1005D => Rpi 3B => Samsung TV or Espon video-projector.
Play with no lags, no stuttering, no problems. Rock stable!

Thanks

**Comment by Funatiq** [comment]
Hi, I'm trying to get this working on libreelec 9.2. When starting the addon I get
"undefined symbol: EVP_CIPHER_CTX_cleanup" [(log)](https://pastebin.com/HES3maw3).
 It seems like this command is deprecated in newer openssl versions. Would it be possible to build the addon with a newer openssl version to fix the error?

**Comment by stuCONNERS1983** [comment]
Is there a latest builds for x64 generic builds of Libreelec? Im currently running 9.1.500 beta

**Comment by ssAxl** [comment]
Hi,

This version is working with Libreelec 9.0 and Geforce 441.41 / GeforceExpericence 3.20.1.57 but not with the last Libreelec 9.2.
Like the last time, can you make some update ? "Please please please" (ask my son... :) )

Bye

**Comment by ssAxl** [comment]
Hi, me again ;)

If this can help, message from my log:
"
_2019-12-10 17:57:11.433 T:1740579712   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.OSError'>
                                            Error Contents: /storage/.kodi/addons/script.moonlight/lib/libmoonlight-common.so.2.4.10: undefined symbol: EVP_CIPHER_CTX_cleanup
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.moonlight/addon.py", line 78, in <module>
                                                index()
                                              File "/storage/.kodi/addons/script.moonlight/addon.py", line 25, in index
                                                gs = LibGameStream(addon.getAddonInfo("path") + "/lib")
                                              File "/storage/.kodi/addons/script.moonlight/lib/moonlight.py", line 58, in __init__
                                                self.commonlib = ctypes.cdll.LoadLibrary(findlib("libmoonlight-common.so"))
                                              File "/usr/lib/python2.7/ctypes/__init__.py", line 444, in LoadLibrary
                                              File "/usr/lib/python2.7/ctypes/__init__.py", line 366, in __init__
                                            OSError: /storage/.kodi/addons/script.moonlight/lib/libmoonlight-common.so.2.4.10: undefined symbol: EVP_CIPHER_CTX_cleanup
                                            -->End of Python script error report<--
2019-12-10 17:57:11.523 T:1748972416   ERROR: GetDirectory - Error getting plugin://script.moonlight/
2019-12-10 17:57:11.523 T:1936779712   ERROR: CGUIMediaWindow::GetDirectory(plugin://script.moonlight/) failed_
"
Sorry to insist, but it's the very best solution I found to stream my pc.

Thanks!
Axl

**Comment by dead** [comment]
Hi @ssAxl sorry for taking so long, but I was really busy...
Just compiled the addon to LibreElec 9.2, so can you please test it?
Thanks!

[script.moonlight-9.2.0.241.zip](https://github.com/dead/script.moonlight/files/3988688/script.moonlight-9.2.0.241.zip)

**Comment by ssAxl** [comment]
Hi @dead,

No problem! I'm (really!) happy for your answer.
I test it this as soon as possible, and give you feedback ;)
Thanks ;)

**Comment by ssAxl** [comment]
Again! :)

It doesn't work for now.
I've cleanup previous install, isntaller with zip, paired with my computer.
I can see game list, but when I choose one, Libreeelc reboot.

Here is my "service.log"
_stream -packetsize 1024 -bitrate 10000 -720 -fps 30 -app "PC-Axl" -keydir "/storage/.kodi/userdata/addon_data/script.moonlight/keys" -mapping "/storage/.kodi/userdata/addon_data/script.moonlight/gamecontrollerdb.txt" 192.168.0.210
/storage/.kodi/addons/script.moonlight/bin/moonlight: error while loading shared libraries: libgamestream.so.4: cannot open shared object file: No such file or directory_

Thanks !! :)

**Comment by dead** [comment]
[script.moonlight-9.2.0.241.zip](https://github.com/dead/script.moonlight/files/3989611/script.moonlight-9.2.0.241.zip)
Should work now!

**Comment by ssAxl** [comment]
Olà!

You're the man! I would like to know to do that!!!!
After some speed test, just some audio bugs.

Thanks again! For now my son is on my shoulder, look at me playing game computer on tv.... and this is not a joke!!! :)

Some feedback later ;)

ssAxl

**Comment by EmiyaBestBoy** [comment]
I'm sorry if this has been answered before but how is this setup exactly? I installed the script you posted 5 days ago and put in my IP, it doesn't work. Is this only for raspberry pi? I'm running Libreelec 9.2.0 on an old x86 64bit pc. I'm not sure how to find the log, I only see settings.xml. Geforce Experience Version: 3.20.2.34

Edit I got the log from Kodi Logfile uploader since I couldn't find service.log:
 ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.OSError'>
                                            Error Contents: /storage/.kodi/addons/script.moonlight/lib/libmoonlight-common.so.4: wrong ELF class: ELFCLASS32
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.moonlight/addon.py", line 78, in <module>
                                                index()
                                              File "/storage/.kodi/addons/script.moonlight/addon.py", line 25, in index
                                                gs = LibGameStream(addon.getAddonInfo("path") + "/lib")
                                              File "/storage/.kodi/addons/script.moonlight/lib/moonlight.py", line 58, in __init__
                                                self.commonlib = ctypes.cdll.LoadLibrary(findlib("libmoonlight-common.so"))
                                              File "/usr/lib/python2.7/ctypes/__init__.py", line 444, in LoadLibrary
                                              File "/usr/lib/python2.7/ctypes/__init__.py", line 366, in __init__
                                            OSError: /storage/.kodi/addons/script.moonlight/lib/libmoonlight-common.so.4: wrong ELF class: ELFCLASS32
                                            -->End of Python script error report<--
2019-12-26 06:43:09.606 T:139680435361536   ERROR: GetDirectory - Error getting plugin://script.moonlight/
2019-12-26 06:43:09.616 T:139682237966464   ERROR: CGUIMediaWindow::GetDirectory(plugin://script.moonlight/) failed

**Comment by dead** [comment]
@EmiyaBestBoy 
Just compiled the x86_64 version of the addon.
Not sure if this will work.

[script.moonlight-9.2.0.241.zip](https://github.com/dead/script.moonlight/files/4003144/script.moonlight-9.2.0.241.zip)

**Comment by EmiyaBestBoy** [comment]
The addon opened this time and showed me my games but selecting a game doesn't do anything. I didn't get any errors either so I don't have any logs to upload.

**Comment by dead** [comment]
@EmiyaBestBoy can you try run moonlight via ssh? just connect to libreelec via ssh, stop kodi `systemctl stop kodi` and then execute `moonlight stream`

**Comment by EmiyaBestBoy** [comment]
Can you walk me through this? I've never used ssh before, I'm getting "Permission denied (publickey,keyboard-interactive)."

**Comment by EmiyaBestBoy** [comment]
Nevermind I got it working, but I got "You must pair with the PC first" even though I've already paired it before?

Edit: I got it to work but it immediately started steam and only half of the screen was mirrored.

**Comment by dead** [comment]
Only half of the screen? Sorry, without a x86_64 to test myself is kinda hard to tell what is wrong 😢

**Comment by EmiyaBestBoy** [comment]
Ah no it’s fine, my Fire stick 4K is arriving on Monday. I’ll keep testing new builds if you want.

**Comment by ssAxl** [comment]
@ Dead,

 On Rpi, have some audio and video lag, but on some games only (1997 moto racer...).
Witcher, and other Rime runs just fine!

Glad to see other people interested in your app!

ssAxl

**Comment by dead** [comment]
@ssAxl Can you test if this build solves your audio issues?
[script.moonlight-9.2.0.241.zip](https://github.com/dead/script.moonlight/files/4016140/script.moonlight-9.2.0.241.zip)

**Comment by ssAxl** [comment]
Hi!
@dead,

In this release I have an error in the service.log:
"stream -packetsize 2048 -bitrate 20000 -1080 -fps 60 -localaudio -nosops -remote -app "PC-Axl" -keydir "/storage/.kodi/userdata/addon_data/script.moonlight/keys" -mapping "/storage/.kodi/userdata/addon_data/script.moonlight/gamecontrollerdb.txt" 192.168.0.210
Unable to open custom mapping file: /storage/.kodi/userdata/addon_data/script.moonlight/gamecontrollerdb.txt"
I've found the missing files in etc directory and paste it in the script.moonlight directory.
So, I've test it, and still the same audio issues: sound cuts time to time for 2-3 seconds.

Thanks again and again for your works and your help!

ssAxl

**Comment by Seldon2K** [comment]
Hi!

@dead 

I'm on Raspberry Pi 4 with LibreElec 9.2. I've been able to launch moonlight from command line and everything works fine. However launching from the addon does not work completely. It starts and I can pair, config, and I can see my games and mstsc. If I select one of these nothing happens.

I have copied script.moonlight.service from /.kodi/addons/script.moonlight/system.d to /.config/system.d and enabled the service with systemctl enable script.moonlight.service. After this, it seems it's beginning to work a bit, but when I launch the addon (launch mstsc), Kodi stops and then suddenly my TV looses HDMI signal. Weird thing is that if I start Kodi again from command line, then my PC desktops appears and I can use it.

Thanks for the great work!!!

**Comment by dead** [comment]
Hi @Seldon2K 
I dont think moonlight-embedded supports RPi 4. :(

**Comment by bite-your-idols** [comment]
@Seldon2K did you get it running on your RPi4?

Last night I tried it in my 2Gb RPi4 running latest official LE. 

Firstly, addon didn't work, after that I tried exiting kodi and using CLI and it paired OK. But I get 

> "Please specify mapping file as default mapping could not be found."

 after trying to launch an app from the list.

After that I came back to kodi and then addon worked OK, it paired again and shows me the list of Gforce apps/games, but when I click on one of them nothing happens...

To make sure it was not a network, PC or firewall issue, I tried it with my PSVita and it launched the game and streamed it very well.

**Comment by bite-your-idols** [comment]
UPDATE: I solve that issue about mapping file but now I get this one:

> Initializing platform...done
Resolving host name...done
Starting RTSP handshake...done
Initializing control stream...done
Initializing video stream...done
Initializing audio stream...done
Initializing input stream...done
Starting control stream...done
Starting video stream...done
Starting audio stream...done
Starting input stream...done
Error: cannot keep up

And the screen on my TV disappears...

**Comment by bite-your-idols** [comment]
New Update:
Finally, yesterday I made it work in my RPi4 running LE 9.2

When I try to launch an app using the addon nothing works.
When I exit kodi and try to launch moonlight using CLI, my display vanished and I need to reboot to make it come back.
When I try to launch moonlight CLI without killing kodi, it works OK!!! 

The only issue is that when I quit the game my RPi freezes and I need to reboot.

I'm going to try to play around a little with the code in addon files...

**Comment by diggidre** [comment]
@bite-your-idols 
Can you please provide further instructions on how you managed running it on RPI4 with LE? Which script version did you use, the last posted in this thread?

**Comment by bite-your-idols** [comment]
I just downloaded the latest zip from this issue.
I installed it, then connect to my RPi via SSH and using CLI commands I get it running, after struggling within some noob issues.
Here you have CLI commands info: https://github.com/irtimmer/moonlight-embedded/wiki/Usage

**Comment by StalkerUKCG** [comment]
Can confirm working on a RPi4 via SSH launching. However the interface within Kodi doesn't work. It will display a list of available games but clicking them does nothing.

I'd love an update to get this working if possible.

**Comment by ssAxl** [comment]
Hi @dead ! how are you?

Me again! :)
I'm still with my Rasp3b but moonlight not working anymore.
I use Libreelec 9.2.8, files for moonlight in this thread with driver Nvidia 511.23 and Geforce experience 3.24.0.126.
Moonlight show game list (and MSTSC.EXE to stream pc desktop), but when I launch streaming, I'm stuck on a black screen.

Services.log show:
stream -packetsize 2048 -bitrate 20000 -720 -fps 60 -localaudio -nosops -remote -app "PC-Axl" -keydir "/storage/.kodi/userdata/addon_data/script.moonlight/keys" ->

Can you try to update it?

Thanks!

**Comment by Frostoman** [comment]
>  Moonlight show game list (and MSTSC.EXE to stream pc desktop), but when I launch streaming, I'm stuck on a black screen.

Nvidia discontinued that capability in latest driver updates. Try to use Sunshine (https://github.com/LizardByte/Sunshine).

Or use Docker based addon. It works with Sunshine: https://github.com/clarkemw/script.moonlight-embedded-launcher
